site_name: pride
pages:
- ['index.md', 'Homepage']
- ['pride\additional_builtins.md', 'pride', 'additional_builtins']
- ['pride\additional_keywords.md', 'pride', 'additional_keywords']
- ['pride\asciitest.md', 'pride', 'asciitest']
- ['pride\asymmetrictest.md', 'pride', 'asymmetrictest']
- ['pride\authentication2.md', 'pride', 'authentication2']
- ['pride\base.md', 'pride', 'base']
- ['pride\blackbox.md', 'pride', 'blackbox']
- ['pride\browser.md', 'pride', 'browser']
- ['pride\contextmanagers.md', 'pride', 'contextmanagers']
- ['pride\cryptographyless.md', 'pride', 'cryptographyless']
- ['pride\database.md', 'pride', 'database']
- ['pride\datastructures.md', 'pride', 'datastructures']
- ['pride\datatransfer.md', 'pride', 'datatransfer']
- ['pride\decorators.md', 'pride', 'decorators']
- ['pride\dtstest.md', 'pride', 'dtstest']
- ['pride\errors.md', 'pride', 'errors']
- ['pride\executable2.md', 'pride', 'executable2']
- ['pride\fileio.md', 'pride', 'fileio']
- ['pride\hkdf.md', 'pride', 'hkdf']
- ['pride\importers.md', 'pride', 'importers']
- ['pride\__main__.md', 'pride', '__main__']
- ['pride\loadtest.md', 'pride', 'loadtest']
- ['pride\main.md', 'pride', 'main']
- ['pride\make_setup.md', 'pride', 'make_setup']
- ['pride\malbolge.md', 'pride', 'malbolge']
- ['pride\metaclass.md', 'pride', 'metaclass']
- ['pride\module_utilities.md', 'pride', 'module_utilities']
- ['pride\network.md', 'pride', 'network']
- ['pride\networkssl.md', 'pride', 'networkssl']
- ['pride\networkutilities.md', 'pride', 'networkutilities']
- ['pride\objectfinder.md', 'pride', 'objectfinder']
- ['pride\package.md', 'pride', 'package']
- ['pride\patch.md', 'pride', 'patch']
- ['pride\persistence.md', 'pride', 'persistence']
- ['pride\preprocessing.md', 'pride', 'preprocessing']
- ['pride\recordservice.md', 'pride', 'recordservice']
- ['pride\rpc.md', 'pride', 'rpc']
- ['pride\securedatatransfer.md', 'pride', 'securedatatransfer']
- ['pride\security.md', 'pride', 'security']
- ['pride\shell.md', 'pride', 'shell']
- ['pride\shell_launcher.md', 'pride', 'shell_launcher']
- ['pride\site_config.md', 'pride', 'site_config']
- ['pride\timingcomparison.md', 'pride', 'timingcomparison']
- ['pride\user.md', 'pride', 'user']
- ['pride\utilities.md', 'pride', 'utilities']
- ['pride\vcs.md', 'pride', 'vcs']
- ['pride\vmlibrary.md', 'pride', 'vmlibrary']
- ['pride\_compile.md', 'pride', '_compile']
- ['pride\_termsize.md', 'pride', '_termsize']
- ['audio\audiolibrary.md', 'audio', 'audiolibrary']
- ['audio\audio_config_utility.md', 'audio', 'audio_config_utility']
- ['audio\capture_live_audio.md', 'audio', 'capture_live_audio']
- ['audio\play_wav_file.md', 'audio', 'play_wav_file']
- ['audio\portaudiodevices.md', 'audio', 'portaudiodevices']
- ['crypto\aestest.md', 'crypto', 'aestest']
- ['crypto\aes_procedures.md', 'crypto', 'aes_procedures']
- ['crypto\augpake.md', 'crypto', 'augpake']
- ['crypto\bitpermutation.md', 'crypto', 'bitpermutation']
- ['crypto\bitpermutationtest.md', 'crypto', 'bitpermutationtest']
- ['crypto\blockcipher.md', 'crypto', 'blockcipher']
- ['crypto\blockcipher2.md', 'crypto', 'blockcipher2']
- ['crypto\blockcipher3.md', 'crypto', 'blockcipher3']
- ['crypto\branchcount.md', 'crypto', 'branchcount']
- ['crypto\collisionreference.md', 'crypto', 'collisionreference']
- ['crypto\collisiontesting.md', 'crypto', 'collisiontesting']
- ['crypto\collisiontesting2.md', 'crypto', 'collisiontesting2']
- ['crypto\convert2test.md', 'crypto', 'convert2test']
- ['crypto\cryptochallengeprogress.md', 'crypto', 'cryptochallengeprogress']
- ['crypto\cryptosecipher.md', 'crypto', 'cryptosecipher']
- ['crypto\crypttest.md', 'crypto', 'crypttest']
- ['crypto\cyclelengthtest.md', 'crypto', 'cyclelengthtest']
- ['crypto\deadbeeftest.md', 'crypto', 'deadbeeftest']
- ['crypto\decorrelationtest.md', 'crypto', 'decorrelationtest']
- ['crypto\decorrelationtest2.md', 'crypto', 'decorrelationtest2']
- ['crypto\diffusiontechniques.md', 'crypto', 'diffusiontechniques']
- ['analysis\algebraicnormalform.md', 'analysis', 'algebraicnormalform']
- ['analysis\cryptanalysis.md', 'analysis', 'cryptanalysis']
- ['analysis\differential.md', 'analysis', 'differential']
- ['analysis\linear.md', 'analysis', 'linear']
- ['analysis\metrics.md', 'analysis', 'metrics']
- ['analysis\visualization.md', 'analysis', 'visualization']
- ['designs\ciphercomponents.md', 'designs', 'ciphercomponents']
- ['blockcipher\aes_procedures.md', 'blockcipher', 'aes_procedures']
- ['blockcipher\blockcipher.md', 'blockcipher', 'blockcipher']
- ['blockcipher\blockcipher2.md', 'blockcipher', 'blockcipher2']
- ['blockcipher\blockcipher3.md', 'blockcipher', 'blockcipher3']
- ['blockcipher\blockcipher4.md', 'blockcipher', 'blockcipher4']
- ['blockcipher\booleanblockcipher.md', 'blockcipher', 'booleanblockcipher']
- ['blockcipher\speck.md', 'blockcipher', 'speck']
- ['blockcipher\_aes.md', 'blockcipher', '_aes']
- ['hash\hmhashtest.md', 'hash', 'hmhashtest']
- ['hash\sponge.md', 'hash', 'sponge']
- ['hash\sponges.md', 'hash', 'sponges']
- ['permutation\booleanpermutation.md', 'permutation', 'booleanpermutation']
- ['permutation\booleanpermutation2.md', 'permutation', 'booleanpermutation2']
- ['permutation\coreprf.md', 'permutation', 'coreprf']
- ['permutation\coreprf2.md', 'permutation', 'coreprf2']
- ['permutation\crx.md', 'permutation', 'crx']
- ['permutation\permutation3.md', 'permutation', 'permutation3']
- ['permutation\permutation4.md', 'permutation', 'permutation4']
- ['permutation\permutetest10.md', 'permutation', 'permutetest10']
- ['permutation\permutetest11.md', 'permutation', 'permutetest11']
- ['permutation\permutetest13.md', 'permutation', 'permutetest13']
- ['permutation\permutetest3.md', 'permutation', 'permutetest3']
- ['permutation\permutetest4.md', 'permutation', 'permutetest4']
- ['permutation\permutetest5.md', 'permutation', 'permutetest5']
- ['permutation\permutetest6.md', 'permutation', 'permutetest6']
- ['permutation\permutetest7.md', 'permutation', 'permutetest7']
- ['permutation\permutetest9.md', 'permutation', 'permutetest9']
- ['streamcipher\booleanstreamcipher.md', 'streamcipher', 'booleanstreamcipher']
- ['streamcipher\rng.md', 'streamcipher', 'rng']
- ['streamcipher\streamcipher.md', 'streamcipher', 'streamcipher']
- ['streamcipher\streamcipher2.md', 'streamcipher', 'streamcipher2']
- ['functions\contextmanagers.md', 'functions', 'contextmanagers']
- ['functions\cryptographyless.md', 'functions', 'cryptographyless']
- ['functions\decorators.md', 'functions', 'decorators']
- ['functions\dpapi.md', 'functions', 'dpapi']
- ['functions\hkdf.md', 'functions', 'hkdf']
- ['functions\module_utilities.md', 'functions', 'module_utilities']
- ['functions\networkutilities.md', 'functions', 'networkutilities']
- ['functions\persistence.md', 'functions', 'persistence']
- ['functions\security.md', 'functions', 'security']
- ['functions\timingcomparison.md', 'functions', 'timingcomparison']
- ['functions\utilities.md', 'functions', 'utilities']
- ['gui\audio_player.md', 'gui', 'audio_player']
- ['gui\blackbox.md', 'gui', 'blackbox']
- ['gui\boardgame.md', 'gui', 'boardgame']
- ['gui\chess.md', 'gui', 'chess']
- ['gui\cyvasse.md', 'gui', 'cyvasse']
- ['gui\datatypes.md', 'gui', 'datatypes']
- ['gui\fileexplorer.md', 'gui', 'fileexplorer']
- ['gui\grid.md', 'gui', 'grid']
- ['gui\messenger.md', 'gui', 'messenger']
- ['gui\pyobjecttest.md', 'gui', 'pyobjecttest']
- ['gui\sdllibrary.md', 'gui', 'sdllibrary']
- ['gui\shell.md', 'gui', 'shell']
- ['gui\text_editor.md', 'gui', 'text_editor']
- ['objectlibrary\authentication3.md', 'objectlibrary', 'authentication3']
- ['objectlibrary\autodocumentation.md', 'objectlibrary', 'autodocumentation']
- ['objectlibrary\base.md', 'objectlibrary', 'base']
- ['objectlibrary\blackbox.md', 'objectlibrary', 'blackbox']
- ['objectlibrary\database.md', 'objectlibrary', 'database']
- ['objectlibrary\datastructures.md', 'objectlibrary', 'datastructures']
- ['objectlibrary\datatransfer.md', 'objectlibrary', 'datatransfer']
- ['objectlibrary\encryptedstorage.md', 'objectlibrary', 'encryptedstorage']
- ['objectlibrary\executable2.md', 'objectlibrary', 'executable2']
- ['objectlibrary\fileio.md', 'objectlibrary', 'fileio']
- ['objectlibrary\helloworldrpc.md', 'objectlibrary', 'helloworldrpc']
- ['objectlibrary\interpreter.md', 'objectlibrary', 'interpreter']
- ['objectlibrary\metaclass.md', 'objectlibrary', 'metaclass']
- ['objectlibrary\network.md', 'objectlibrary', 'network']
- ['objectlibrary\networkssl.md', 'objectlibrary', 'networkssl']
- ['objectlibrary\package.md', 'objectlibrary', 'package']
- ['objectlibrary\patch.md', 'objectlibrary', 'patch']
- ['objectlibrary\rpc.md', 'objectlibrary', 'rpc']
- ['objectlibrary\shell.md', 'objectlibrary', 'shell']
- ['objectlibrary\storage.md', 'objectlibrary', 'storage']
- ['objectlibrary\user.md', 'objectlibrary', 'user']
- ['objectlibrary\vcs.md', 'objectlibrary', 'vcs']
- ['objectlibrary\vmlibrary.md', 'objectlibrary', 'vmlibrary']
- ['objectlibrary\_termsize.md', 'objectlibrary', '_termsize']
- ['programs\create_documentation.md', 'programs', 'create_documentation']
- ['programs\create_self_signed_certificate.md', 'programs', 'create_self_signed_certificate']
- ['programs\make_setup.md', 'programs', 'make_setup']
- ['programs\register.md', 'programs', 'register']
- ['programs\shell_launcher.md', 'programs', 'shell_launcher']
- ['programs\stupidreceive.md', 'programs', 'stupidreceive']
- ['programs\stupidsend.md', 'programs', 'stupidsend']
- ['programs\tcp_scanner.md', 'programs', 'tcp_scanner']
- ['programs\unzip.md', 'programs', 'unzip']
- ['programs\_compile.md', 'programs', '_compile']
- ['pride\pride.md', 'pride', 'pride']
